{
  "header": "Extrinsic #18278717-3",
  "infoTable": [
    [
      "Network",
      "Polkadot"
    ],
    [
      "Timestamp",
      "22 Nov 2023 12:16:06 (UTC)"
    ],
    [
      "Block time",
      ""
    ],
    [
      "Hash",
      "0xc06d2f1b8c460e8221a6cfec6e406064d7c5720b26374f8018b39d3ced792d31"
    ],
    [
      "Block",
      "18278717"
    ],
    [
      "Account",
      "1qnJN7FViy3HZaxZK9tGAA71zxHSBeUweirKqCaox4t8GT7"
    ],
    [
      "Result",
      "Success"
    ],
    [
      "Name",
      "Utility.batch_all"
    ],
    [
      "Parameters",
      "Parsed\nRaw\ncalls\n\t\n0\n\t\nBalances\n\t\ntransfer_allow_death\n\t\n2862403449700\n\n\n1\n\t\nBalances\n\t\ntransfer_allow_death\n\t\n309566836000\n\n\n2\n\t\nBalances\n\t\ntransfer_allow_death\n\t\n114834724000"
    ],
    [
      "Fee",
      "249583871"
    ],
    [
      "Signature",
      "0xe53457b43eee7db5ec4c3eeaf230089b6619e107cacd2e3cff6bbbdbe4ed764e2540d7869a81a8fbd9a9c87cd24cfae878a40ac6de51bec67e6a91452050df02"
    ],
    [
      "Spec version",
      "9431"
    ]
  ],
  "notFoundHeader": "Extrinsic #18278717-3",
  "notFound": "No extrinsic found",
  "errorHeader": "Extrinsic #18278717-3",
  "error": "Unexpected error occured while fetching dataThis error is logged. No need to report it.DetailsExtrinsic error"
}